const songs = [ // eslint-disable-line no-unused-vars
  ['Queen', 'Bohemian Rhapsody', 'fJ9rUzIMcZQ'],
  ['Queen', 'Don\'t Stop Me Now', 'HgzGwKwLmgM'],
  ['Queen', 'Another One Bites The Dust', 'rY0WxgSXdEE'],
  ['Queen', 'We Will Rock You', '-tJYN-eG1zk'],
  ['Queen', 'We Are The Champions', '04854XqcfCY'],
  ['Queen', 'Radio Ga Ga', 'azdwsXLmrHE'],
  ['Queen', 'The Show Must Go On', 't99KH0TR-J4'],
  ['Coldplay', 'The Scientist', 'RB-RcX5DS5A'],
  ['Coldplay', 'Yellow', 'yKNxeF4KMsY'],
  ['Coldplay', 'Viva La Vida', 'dvgZkm1xWPE'],
  ['Coldplay', 'Fix You', 'k4V3Mo61fJM'],
  ['Coldplay', 'Paradise', '1G4isv_Fylg'],
  ['Coldplay', 'Clocks', 'd020hcWA_Wg'],
  ['The Offspring', 'The Kids Aren\'t Alright', '7iNbnineUCI'],
  ['The Offspring', 'Self Esteem', 'Abrn8aVQ76Q'],
  ['The Offspring', 'Pretty Fly (For A White Guy)', 'QtTR-_Klcq8'],
  ['The Offspring', 'Why Don\'t You Get A Job', 'LH-i8IvYIcg'],
  ['The Offspring', 'Want You Bad', '_g19fCJotPc'],
  ['The Offspring', 'Gone Away', '40V9_1PMUGM'],
  ['Guns N\' Roses', 'Sweet Child O\' Mine', '1k8craCGpgs'],
  ['Guns N\' Roses', 'Paradise City', 'Rbm6GXllBiw'],
  ['Guns N\' Roses', 'November Rain', '8SbUC-UaAxE'],
  ['Guns N\' Roses', 'Knockin\' On Heaven\'s Door', 'k04tX2fvh0o'],
  ['Guns N\' Roses', 'Don\'t Cry', 'zRIbf6JqkNc'],
  ['Metallica', 'Nothing Else Matters', 'tAGnKpE4NCI'],
  ['Metallica', 'The Unforgiven', 'DDGhKS6bSAE'],
  ['Metallica', 'Fade To Black', '9HZ_tx8aWuA'],
  ['Metallica', 'The Day That Never Comes', 'RD83oy7ksUE'],
  ['The Cranberries', 'Zombie', '6Ejga4kJUts'],
  ['The Cranberries', 'Ode To My Family', 'Zz-DJr1Qs54'],
  ['The Cranberries', 'Dreams', 'Yam5uK6e-bQ'],
  ['The Cranberries', 'Linger', 'G6Kspj3OO0s'],
  ['Red Hot Chili Peppers', 'Californication', 'YlUKcNNmywk'],
  ['Red Hot Chili Peppers', 'Otherside', 'rn_YodiJO6k'],
  ['Red Hot Chili Peppers', 'Can\'t Stop', '8DyziWtkfBw'],
  ['Red Hot Chili Peppers', 'By The Way', 'JnfyjwChuNU'],
  ['Sum 41', 'Fat Lip', 'CMX2lPum_pg'],
  ['Sum 41', 'Still Waiting', 'qO-mSLxih-c'],
  ['Sum 41', 'The Hell Song', '7pE8ReA5cn4'],
  ['Sum 41', 'Pieces', 'By7ctqcWxyM'],
  ['blink-182', 'All The Small Things', '9Ht5RZpzPqw'],
  ['blink-182', 'I Miss You', 's1tAYmMjLdY'],
  ['blink-182', 'First Date', 'vVy9Lgpg1m8'],
  ['blink-182', 'Adam\'s Song', '2MRdtXWcgIw'],
  ['The Rasmus', 'In The Shadows', '7gwO8-oqwFw'],
  ['The Rasmus', 'Guilty', 'eOdr_FlBPBk'],
  ['The Rasmus', 'Sail Away', 'pL-i4Lcgk2w'],
  ['The Rasmus', 'First Day Of My Life', 'oBvbX571P3s'],
  ['Rise Against', 'Savior', 'e8X3ACToii0'],
  ['Rise Against', 'Prayer Of The Refugee', '9-SQGOYOjxs'],
  ['Rise Against', 'Hero Of War', '_DboMAghWcA'],
  ['Rise Against', 'Give It All', 'dhldbymXK-8'],
  ['Linkin Park', 'In The End', 'eVTXPUF4Oz4'],
  ['Linkin Park', 'Numb', 'kXYiU_JCYtU'],
  ['Linkin Park', 'What I\'ve Done', '8sgycukafqQ'],
  ['Green Day', 'Wake Me Up When September Ends', 'NU9JoFKlaZ0'],
  ['Green Day', 'Boulevard Or Broken Dreams', 'Soa3gO7tL-c'],
  ['Green Day', 'Holiday', 'A1OqtIqzScI'],
  ['System Of A Down', 'Chop Suey!', '1k8craCGpgs'],
  ['System Of A Down', 'Aerials', 'L-iepu3EtyE'],
  ['System Of A Down', 'Lonely Day', 'DnGdoEa1tPg'],
  ['Nirvana', 'Smells Like Teen Spirit', 'hTWKbfoikeg'],
  ['Nirvana', 'Come As You Are', 'ZEMBDKMtHqM'],
  ['Nirvana', 'Lithium', 'pkcJEvMcnEg'],
  ['Oasis', 'Wonderwall', 'bx1Bh8ZvH84'],
  ['Oasis', 'Don\'t Look Back In Anger', 'r8OipmKFDeM'],
  ['Oasis', 'Stop Crying Your Heart Out', '6QyVil0dwhk'],
  ['Scorpions', 'Wind Of Change', 'n4RjJKxsamQ'],
  ['Scorpions', 'Rock You Like A Hurricane', 'UCxgbOBVSfM'],
  ['Scorpions', 'Send Me An Angel', '1UUYjd2rjsE'],
  ['Aerosmith', 'I Don\'t Want To Miss A Thing', 'JkK8g6FMEXE'],
  ['Aerosmith', 'Crazy', 'NMNgbISmF4I'],
  ['Aerosmith', 'Cryin\'', 'qfNmyxV2Ncw'],
  ['R.E.M.', 'Losing My Religion', 'xwtdhWltSIg'],
  ['R.E.M.', 'Everybody Hurts', '5rOiW_xY-kc'],
  ['R.E.M.', 'Shiny Happy People', 'YYOKMUTTDdA'],
  ['The Beatles', 'Come Together', '45cYwDMibGo'],
  ['The Beatles', 'Let It Be', 'QDYfEBY9NM4'],
  ['The Beatles', 'Hey Jude', 'A_MjCqQoLLA'],
  ['Papa Roach', 'Last Resort', 'j0lSpNtjPM8'],
  ['Papa Roach', 'Scars', 'eHbNU9WuVgw'],
  ['Papa Roach', 'Between Angels And Insects', 'H2jCbXiEQI4'],
  ['Limp Bizkit', 'Rollin\'', 'RYnFIRc0k6E'],
  ['Limp Bizkit', 'Behind Blue Eyes', 'Tr8uesBowS4'],
  ['Limp Bizkit', 'My Way', 'Dn8vzTsnPps'],
  ['Rammstein', 'Du Hast', '04854XqcfCY'],
  ['Rammstein', 'Amerika', 'Rr8ljRgcJNM'],
  ['Rammstein', 'Ohne Dich', 'LIPc1cfS-oQ'],
  ['3 Doors Down', 'Kryptonite', 'xPU8OAjjS4k'],
  ['3 Doors Down', 'Here Without You', 'kPBzTxZQG5Q'],
  ['3 Doors Down', 'When I\'m Gone', 'pFq1eT9tMJ4'],
  ['Bon Jovi', 'Livin\' On A Prayer', 'lDK9QqIzhwk'],
  ['Bon Jovi', 'You Give Love A Bad Name', 'KrZHPOeOxQQ'],
  ['Bon Jovi', 'It\'s My Life', 'vx2u5uUu3DE'],
  ['Duran Duran', 'Hungry Like The Wolf', 'oJL-lCzEXgI'],
  ['Duran Duran', 'Come Undone', 'Epj84QVw2rc'],
  ['Duran Duran', 'Ordinary World', 'FqIACCH20JU'],
  ['Sting', 'Englishman In New York', 'd27gTrPPAyk'],
  ['Sting', 'Shape Of My Heart', 'NlwIDxCjL-8'],
  ['Sting', 'Desert Rose', 'C3lWwBslWqg'],
  ['Savage Garden', 'Truly Madly Deeply', 'WQnAxOQxQIU'],
  ['Savage Garden', 'I Knew I Loved You', 'jjnmICxvoVY'],
  ['Savage Garden', 'To The Moon & Back', 'HCm6gRHINqA'],
  ['Toto', 'Africa', 'FTQbiNvZqaY'],
  ['Toto', 'Hold the Line', 'htgr3pvBr-I'],
  ['Toto', 'Rosanna', 'qmOLtTGvsbM'],
  ['t.A.T.u.', 'All The Things You Said', '8mGBaXPlri8'],
  ['t.A.T.u.', 'All About Us', '6yP4Nm86yk0'],
  ['t.A.T.u.', 'Not Gonna Get Us', '0HL-N9oOjcs'],
  ['Roxette', 'It Must Have Been Love', 'k2C5TjS2sh4'],
  ['Roxette', 'Listen To Your Heart', 'yCC_b5WHLX0'],
  ['Roxette', 'The Look', 'LlVI7ZNiFlI'],
  ['AC/DC', 'Highway To Hell', '04854XqcfCY'],
  ['AC/DC', 'Thunderstruck', 'v2AC41dglnM'],
  ['Iron Maiden', 'Run To The Hills', '86URGgqONvA'],
  ['Iron Maiden', 'Fear Of The Dark', 'bePCRKGUwAY'],
  ['Joan Jett & The Blackhearts', 'I Love Rock \'N Roll', 'wMsazR6Tnf8'],
  ['Joan Jett & The Blackhearts', 'I Hate Myself For Loving You', 'bpNw7jYkbVc'],
  ['The Verve', 'Bitter Sweet Symphony', '1lyu1KKwC74'],
  ['The Verve', 'The Drugs Don\'t Work', 'ToQ0n3itoII'],
  ['Simple Plan', 'Welcome To My Life', 'r0U0AlLVqpk'],
  ['Simple Plan', 'Perfect', 'RUi54JTgL5s'],
  ['Three Days Grace', 'I Hate Everything About You', 'ph9KP2_lT5Q'],
  ['Three Days Grace', 'Never Too Late', 'lL2ZwXj1tXM'],
  ['Thirty Seconds To Mars', 'The Kill', '8yvGCAvOAfM'],
  ['Thirty Seconds To Mars', 'This Is War', 'Zcps2fJKuAI'],
  ['Alphaville', 'Big In Japan', 'tl6u2NASUzU'],
  ['Alphaville', 'Forever Young', 'oNjQXmoxiQ8'],
  ['Evanescence', 'Bring Me To Life', '3YxaaGgTQYM'],
  ['Evanescence', 'My Immortal', '5anLPw0Efmo'],
  ['No Doubt', 'Don\'t Speak', 'TR3Vdo5etCQ'],
  ['No Doubt', 'Just A Girl', 'PHzOOQfhPFg'],
  ['The Police', 'Every Breath You Take', 'OMOGaugKpzs'],
  ['The Police', 'Roxanne', '3T1c7GkzRQQ'],
  ['The Killers', 'Mr. Brightside', '1k8craCGpgs'],
  ['The Killers', 'Somebody Told Me', 'Y5fBdpreJiU'],
  ['4 Non Blondes', 'What\'s Up', '6NXnxTNIWkc'],
  ['a-ha', 'Take On Me', 'djV11Xbc914'],
  ['Alanis Morissette', 'Ironic', 'Jne9t8sHpUc'],
  ['Alice Cooper', 'Poison', 'Qq4j1LtCdww'],
  ['Alien Ant Farm', 'Smooth Criminal', 'CDl9ZMfj6aE'],
  ['Berlin', 'Take My Breath Away', 'Bx51eegLTY8'],
  ['Blur', 'Song 2', 'SSbBvKaM6sk'],
  ['Cutting Crew', '(I Just) Died In Your Arms', '6dOwHzCHfgA'],
  ['Europe', 'The Final Countdown', '9jK-NcRmVcw'],
  ['Hoobastank', 'The Reason', 'fV4DiAyExN0'],
  ['Joan Osbourne', 'One Of Us', 'aDdOnl0bHO4'],
  ['Journey', 'Don\'t Stop Believin\'', '1k8craCGpgs'],
  ['Kiss', 'I Was Made For Lovin\' You', '1k8craCGpgs'],
  ['Liquido', 'Narcotic', 'PJ7E40Ec5ec'],
  ['Placebo', 'Every You Every Me', 'OMaycNcPsHI'],
  ['Radiohead', 'Creep', 'XFkzRNyygfk'],
  ['Run DMC', 'Walk This Way', '4B_UYYPb-Gk'],
  ['Snow Patrol', 'Chasing Cars', 'GemKqzILV4w'],
  ['Survivor', 'Eye Of The Tiger', 'btPJPFnesV4'],
  ['The White Stripes', 'Seven Nation Army', '0J2QdDbelmY'],
  ['Tokio Hotel', 'Monsoon', 'Le_IyYLrUtQ'],
  ['Ugly Kid Joe', 'Cats In The Cradle', 'B32yjbCSVpU']
];
