const songs = [ // eslint-disable-line no-unused-vars
  ['Queen', 'Bohemian Rhapsody', 'fJ9rUzIMcZQ'],
  ['Queen', 'Don\'t Stop Me Now', 'HgzGwKwLmgM'],
  ['Queen', 'Another One Bites The Dust', 'rY0WxgSXdEE'],
  ['Queen', 'We Will Rock You', '-tJYN-eG1zk'],
  ['Queen', 'We Are The Champions', '04854XqcfCY'],
  ['Queen', 'Radio Ga Ga', 'azdwsXLmrHE'],
  ['Queen', 'The Show Must Go On', 't99KH0TR-J4'],
  ['Queen', 'Under Pressure', 'a01QQZyl-_I'],
  ['Coldplay', 'The Scientist', 'RB-RcX5DS5A'],
  ['Coldplay', 'Yellow', 'yKNxeF4KMsY'],
  ['Coldplay', 'Viva La Vida', 'dvgZkm1xWPE'],
  ['Coldplay', 'Fix You', 'k4V3Mo61fJM'],
  ['Coldplay', 'Paradise', '1G4isv_Fylg'],
  ['Coldplay', 'Clocks', 'd020hcWA_Wg'],
  ['The Offspring', 'The Kids Aren\'t Alright', '7iNbnineUCI'],
  ['The Offspring', 'Self Esteem', 'Abrn8aVQ76Q'],
  ['The Offspring', 'Pretty Fly (For A White Guy)', 'QtTR-_Klcq8'],
  ['The Offspring', 'Why Don\'t You Get A Job', 'LH-i8IvYIcg'],
  ['The Offspring', 'Want You Bad', '_g19fCJotPc'],
  ['The Offspring', 'Gone Away', '40V9_1PMUGM'],
  ['Red Hot Chili Peppers', 'Californication', 'YlUKcNNmywk'],
  ['Red Hot Chili Peppers', 'Otherside', 'rn_YodiJO6k'],
  ['Red Hot Chili Peppers', 'Can\'t Stop', '8DyziWtkfBw'],
  ['Red Hot Chili Peppers', 'By The Way', 'JnfyjwChuNU'],
  ['Red Hot Chili Peppers', 'Under The Bridge', 'GLvohMXgcBo'],
  ['Guns N\' Roses', 'Sweet Child O\' Mine', '1w7OgIMMRc4'],
  ['Guns N\' Roses', 'Paradise City', 'Rbm6GXllBiw'],
  ['Guns N\' Roses', 'November Rain', '8SbUC-UaAxE'],
  ['Guns N\' Roses', 'Knockin\' On Heaven\'s Door', 'k04tX2fvh0o'],
  ['Guns N\' Roses', 'Don\'t Cry', 'zRIbf6JqkNc'],
  ['Blondie', 'Heart Of Glass', 'WGU_4-5RaxU'],
  ['Blondie', 'One Way Or Another', 'valVixMpzQY'],
  ['Blondie', 'Call Me', 'StKVS0eI85I'],
  ['Blondie', 'Atomic', 'O_WLw_0DFQQ'],
  ['Blondie', 'Maria', 'abw49k3rIN0'],
  ['David Bowie', 'Starman', 'aBKEt3MhNMM'],
  ['David Bowie', 'Let\'s Dance', 'VbD_kBJc_gI'],
  ['David Bowie', 'Modern Love', 'HivQqTtiHVw'],
  ['David Bowie', 'Space Oddity', 'iYYRH4apXDo'],
  ['Metallica', 'Nothing Else Matters', 'tAGnKpE4NCI'],
  ['Metallica', 'The Unforgiven', 'DDGhKS6bSAE'],
  ['Metallica', 'Fade To Black', '9HZ_tx8aWuA'],
  ['Metallica', 'The Day That Never Comes', 'RD83oy7ksUE'],
  ['The Cranberries', 'Zombie', '6Ejga4kJUts'],
  ['The Cranberries', 'Ode To My Family', 'Zz-DJr1Qs54'],
  ['The Cranberries', 'Dreams', 'Yam5uK6e-bQ'],
  ['The Cranberries', 'Linger', 'G6Kspj3OO0s'],
  ['Sum 41', 'Fat Lip', 'CMX2lPum_pg'],
  ['Sum 41', 'Still Waiting', 'qO-mSLxih-c'],
  ['Sum 41', 'The Hell Song', '7pE8ReA5cn4'],
  ['Sum 41', 'Pieces', 'By7ctqcWxyM'],
  ['blink-182', 'All The Small Things', '9Ht5RZpzPqw'],
  ['blink-182', 'I Miss You', 's1tAYmMjLdY'],
  ['blink-182', 'First Date', 'vVy9Lgpg1m8'],
  ['blink-182', 'Adam\'s Song', '2MRdtXWcgIw'],
  ['The Rasmus', 'In The Shadows', '7gwO8-oqwFw'],
  ['The Rasmus', 'Guilty', 'eOdr_FlBPBk'],
  ['The Rasmus', 'Sail Away', 'pL-i4Lcgk2w'],
  ['The Rasmus', 'First Day Of My Life', 'oBvbX571P3s'],
  ['Rise Against', 'Savior', 'e8X3ACToii0'],
  ['Rise Against', 'Prayer Of The Refugee', '9-SQGOYOjxs'],
  ['Rise Against', 'Hero Of War', '_DboMAghWcA'],
  ['Rise Against', 'Give It All', 'dhldbymXK-8'],
  ['Linkin Park', 'In The End', 'eVTXPUF4Oz4'],
  ['Linkin Park', 'Numb', 'kXYiU_JCYtU'],
  ['Linkin Park', 'What I\'ve Done', '8sgycukafqQ'],
  ['Green Day', 'Wake Me Up When September Ends', 'NU9JoFKlaZ0'],
  ['Green Day', 'Boulevard Or Broken Dreams', 'Soa3gO7tL-c'],
  ['Green Day', 'Holiday', 'A1OqtIqzScI'],
  ['System Of A Down', 'Chop Suey!', 'CSvFpBOe8eY'],
  ['System Of A Down', 'Aerials', 'L-iepu3EtyE'],
  ['System Of A Down', 'Lonely Day', 'DnGdoEa1tPg'],
  ['Nirvana', 'Smells Like Teen Spirit', 'hTWKbfoikeg'],
  ['Nirvana', 'Come As You Are', 'ZEMBDKMtHqM'],
  ['Nirvana', 'Lithium', 'pkcJEvMcnEg'],
  ['Oasis', 'Wonderwall', 'bx1Bh8ZvH84'],
  ['Oasis', 'Don\'t Look Back In Anger', 'r8OipmKFDeM'],
  ['Oasis', 'Stop Crying Your Heart Out', '6QyVil0dwhk'],
  ['Scorpions', 'Wind Of Change', 'n4RjJKxsamQ'],
  ['Scorpions', 'Rock You Like A Hurricane', 'UCxgbOBVSfM'],
  ['Scorpions', 'Send Me An Angel', '1UUYjd2rjsE'],
  ['AC/DC', 'Highway To Hell', 'l482T0yNkeo'],
  ['AC/DC', 'Thunderstruck', 'v2AC41dglnM'],
  ['AC/DC', 'You Shook Me All Night Long', 'Lo2qQmj0_h4'],
  ['Aerosmith', 'I Don\'t Want To Miss A Thing', 'JkK8g6FMEXE'],
  ['Aerosmith', 'Crazy', 'NMNgbISmF4I'],
  ['Aerosmith', 'Cryin\'', 'qfNmyxV2Ncw'],
  ['R.E.M.', 'Losing My Religion', 'xwtdhWltSIg'],
  ['R.E.M.', 'Everybody Hurts', '5rOiW_xY-kc'],
  ['R.E.M.', 'Shiny Happy People', 'YYOKMUTTDdA'],
  ['The Beatles', 'Come Together', '45cYwDMibGo'],
  ['The Beatles', 'Let It Be', 'QDYfEBY9NM4'],
  ['The Beatles', 'Hey Jude', 'A_MjCqQoLLA'],
  ['The Clash', 'Should I Stay or Should I Go', 'BN1WwnEDWAM'],
  ['The Clash', 'London Calling', 'a3XqMtam1I0'],
  ['The Clash', 'Rock the Casbah', 'LJTk64tzduQ'],
  ['The Cure', 'Lovesong', 'ks_qOI0lzho', '1989'],
  ['The Cure', 'Lullaby', 'ijxk-fgcg7c', '1989'],
  ['The Cure', 'Just Like Heaven', 'n3nPiBai66M'],
  ['The Police', 'Every Breath You Take', 'OMOGaugKpzs'],
  ['The Police', 'Roxanne', '3T1c7GkzRQQ'],
  ['The Police', 'Message In A Bottle', 'MbXWrmQW-OE'],
  ['Papa Roach', 'Last Resort', 'j0lSpNtjPM8'],
  ['Papa Roach', 'Scars', 'eHbNU9WuVgw'],
  ['Papa Roach', 'Between Angels And Insects', 'H2jCbXiEQI4'],
  ['Limp Bizkit', 'Rollin\'', 'RYnFIRc0k6E'],
  ['Limp Bizkit', 'Behind Blue Eyes', 'Tr8uesBowS4'],
  ['Limp Bizkit', 'My Way', 'Dn8vzTsnPps'],
  ['Rammstein', 'Du Hast', 'W3q8Od5qJio'],
  ['Rammstein', 'Amerika', 'Rr8ljRgcJNM'],
  ['Rammstein', 'Ohne Dich', 'LIPc1cfS-oQ'],
  ['3 Doors Down', 'Kryptonite', 'xPU8OAjjS4k'],
  ['3 Doors Down', 'Here Without You', 'kPBzTxZQG5Q'],
  ['3 Doors Down', 'When I\'m Gone', 'pFq1eT9tMJ4'],
  ['Bon Jovi', 'Livin\' On A Prayer', 'lDK9QqIzhwk'],
  ['Bon Jovi', 'You Give Love A Bad Name', 'KrZHPOeOxQQ'],
  ['Bon Jovi', 'It\'s My Life', 'vx2u5uUu3DE'],
  ['Duran Duran', 'Hungry Like The Wolf', 'oJL-lCzEXgI'],
  ['Duran Duran', 'Come Undone', 'Epj84QVw2rc'],
  ['Duran Duran', 'Ordinary World', 'FqIACCH20JU'],
  ['Sting', 'Englishman In New York', 'd27gTrPPAyk'],
  ['Sting', 'Shape Of My Heart', 'NlwIDxCjL-8'],
  ['Sting', 'Desert Rose', 'C3lWwBslWqg'],
  ['Savage Garden', 'Truly Madly Deeply', 'WQnAxOQxQIU'],
  ['Savage Garden', 'I Knew I Loved You', 'jjnmICxvoVY'],
  ['Savage Garden', 'To The Moon & Back', 'HCm6gRHINqA'],
  ['Toto', 'Africa', 'FTQbiNvZqaY'],
  ['Toto', 'Hold the Line', 'htgr3pvBr-I'],
  ['Toto', 'Rosanna', 'qmOLtTGvsbM'],
  ['t.A.T.u.', 'All The Things You Said', '8mGBaXPlri8'],
  ['t.A.T.u.', 'All About Us', '6yP4Nm86yk0'],
  ['t.A.T.u.', 'Not Gonna Get Us', '0HL-N9oOjcs'],
  ['Roxette', 'It Must Have Been Love', 'k2C5TjS2sh4'],
  ['Roxette', 'Listen To Your Heart', 'yCC_b5WHLX0'],
  ['Roxette', 'The Look', 'LlVI7ZNiFlI'],
  ['Iron Maiden', 'Run To The Hills', '86URGgqONvA'],
  ['Iron Maiden', 'Fear Of The Dark', 'bePCRKGUwAY'],
  ['Led Zeppelin', 'Immigrant Song', 'RlNhD0oS5pk'],
  ['Led Zeppelin', 'Stairway to Heaven', 'QkF3oxziUI4'],
  ['Pink Floyd', 'Another Brick In The Wall Part 2', 'HrxX9TBj2zY'],
  ['Pink Floyd', 'Wish You Were Here', '84Tq-eAJIk4'],
  ['Joan Jett & The Blackhearts', 'I Love Rock \'N Roll', 'wMsazR6Tnf8'],
  ['Joan Jett & The Blackhearts', 'I Hate Myself For Loving You', 'bpNw7jYkbVc'],
  ['Creedence Clearwater Revival', 'Have You Ever Seen The Rain', 'u1V8YRJnr4Q'],
  ['Creedence Clearwater Revival', 'Fortunate Son', 'ZWijx_AgPiA'],
  ['Elton John', 'Rocket Man', 'DtVBCG6ThDk'],
  ['Elton John', 'Saturday Night\'s Alright (For Fighting)', 'AhnZEmnuzgM'],
  ['Frank Sinatra', 'My Way', 'qQzdAsjWGPg'],
  ['Frank Sinatra', 'Fly Me To The Moon', 'ZEcqHA7dbwM'],
  ['The Verve', 'Bitter Sweet Symphony', '1lyu1KKwC74'],
  ['The Verve', 'The Drugs Don\'t Work', 'ToQ0n3itoII'],
  ['Simple Plan', 'Welcome To My Life', 'r0U0AlLVqpk'],
  ['Simple Plan', 'Perfect', 'RUi54JTgL5s'],
  ['Three Days Grace', 'I Hate Everything About You', 'ph9KP2_lT5Q'],
  ['Three Days Grace', 'Never Too Late', 'lL2ZwXj1tXM'],
  ['Thirty Seconds To Mars', 'The Kill', '8yvGCAvOAfM'],
  ['Thirty Seconds To Mars', 'This Is War', 'Zcps2fJKuAI'],
  ['Alice Cooper', 'Poison', 'Qq4j1LtCdww'],
  ['Alice Cooper', 'School\'s Out', '2Oo8QzDHimQ'],
  ['Alphaville', 'Big In Japan', 'tl6u2NASUzU'],
  ['Alphaville', 'Forever Young', 'oNjQXmoxiQ8'],
  ['Backstreet Boys', 'Everybody (Backstreet\'s Back', '6M6samPEMpM'],
  ['Backstreet Boys', 'I Want It That Way', '4fndeDfaWCg'],
  ['Boney M.', 'Rasputin', '16y1AkoZkmQ'],
  ['Boney M.', 'Daddy Cool', 'FYGTT7YhywA'],
  ['Bonnie Tyler', 'Total Eclipse of the Heart', 'lcOxhH8N3Bo'],
  ['Bonnie Tyler', 'Holding Out For A Hero', 'bWcASV2sey0'],
  ['Cyndi Lauper', 'Girls Just Want To Have Fun', 'PIb6AZdTr-A'],
  ['Cyndi Lauper', 'Time After Time', 'VdQY7BusJNU'],
  ['Whitney Houston', 'I Will Always Love You', '3JWTaaS7LdU'],
  ['Whitney Houston', 'I Wann Dance With Somebody', 'eH3giaIzONA'],
  ['Depeche Mode', 'Personal Jesus', 'u1xrNaTO1bI'],
  ['Depeche Mode', 'Enjoy The Silence', 'aGSKrC7dGcY'],
  ['Eurythmics, Annie Lennox, Dave Stewart', 'Sweet Dreams (Are Made Of This)', 'qeMFqkcPYcg'],
  ['Eurythmics, Annie Lennox, Dave Stewart', 'Here Comes The Rain Again', 'TzFnYcIqj6I'],
  ['Beastie Boys', 'Sabotage', 'z5rRZdiu1UE'],
  ['Beastie Boys', 'Intergalactic', 'qORYO0atB6g'],
  ['Billy Idol', 'Rebel Yell', 'VdphvuyaV_I'],
  ['Billy Idol', 'White Wedding', 'AAZQaYKZMTI'],
  ['Evanescence', 'Bring Me To Life', '3YxaaGgTQYM'],
  ['Evanescence', 'My Immortal', '5anLPw0Efmo'],
  ['No Doubt', 'Don\'t Speak', 'TR3Vdo5etCQ'],
  ['No Doubt', 'Just A Girl', 'PHzOOQfhPFg'],
  ['The Cardigans', 'Lovefool', 'NI6aOFI7hms', '1996'],
  ['The Cardigans', 'My Favourite Game', 'u9WgtlgGAgs'],
  ['The Killers', 'Mr. Brightside', 'gGdGFtwCNBE'],
  ['The Killers', 'Somebody Told Me', 'Y5fBdpreJiU'],
  ['4 Non Blondes', 'What\'s Up', '6NXnxTNIWkc'],
  ['a-ha', 'Take On Me', 'djV11Xbc914'],
  ['Ace of Base', 'All That She Wants', 'd73tiBBzvFM'],
  ['Alanis Morissette', 'Ironic', 'Jne9t8sHpUc'],
  ['Alien Ant Farm', 'Smooth Criminal', 'CDl9ZMfj6aE'],
  ['Bee Gees', 'Stayin\' Alive', 'I_izvAbhExY'],
  ['Berlin', 'Take My Breath Away', 'Bx51eegLTY8'],
  ['Black Sabbath', 'Paranoid', '0qanF-91aJo'],
  ['Blind Melon', 'No Rain', '3qVPNONdF58'],
  ['Blur', 'Song 2', 'SSbBvKaM6sk'],
  ['Bomfunk MC\'s', 'Freestyler', 'ymNFyxvIdaM'],
  ['Bronski Beat', 'Smalltown Boy', '88sARuFu-tc'],
  ['Chumbawamba', 'Tubthumping', '2H5uWRjFsGc'],
  ['Coolio', 'Gangsta\'s Paradise', 'fPO76Jlnz6c'],
  ['Cutting Crew', '(I Just) Died In Your Arms', '6dOwHzCHfgA'],
  ['Dead Or Alive', 'You Spin Me Round (Like A Record)', 'PGNiXGX2nLU'],
  ['Deep Purple', 'Smoke On The Water', 'eu5lv2Umn3M'],
  ['Dire Straits', 'Sultans of Swing', 'h0ffIJ7ZO4U'],
  ['Don Henley', 'The Boys Of Summer', '6RUIeX6UCT8'],
  ['Eagles', 'Hotel California', 'BciS5krYL80'],
  ['Empire Of The Sun', 'We Are The People', 'hN5X4kGhAtU'],
  ['Earth, Wind & Fire', 'September', 'Gs069dndIYk'],
  ['Europe', 'The Final Countdown', '9jK-NcRmVcw'],
  ['Falco', 'Rock Me Amadeus', 'cVikZ8Oe_XA'],
  ['Fleetwood Mac', 'Go Your Own Way', 'ozl3L9fhKtE'],
  ['Foster The People', 'Pumped Up Kicks', 'SDTZ7iX4vTQ'],
  ['Frankie Goes To Hollywood', 'Relax', 'Yem_iEHiyJ0'],
  ['Frankie Valli and the Four Seasons', 'Can\' Take My Eyes Off You', 'DYwQy_9JPtQ'],
  ['Gorillaz', 'Feel Good Inc.', 'HyHNuVaZJ-k'],
  ['Hoobastank', 'The Reason', 'fV4DiAyExN0'],
  ['Iggy Pop', 'The Passenger', '-fWw7FE9tTo'],
  ['INXS', 'Need You Tonight', 'F93ywiGMDnQ'],
  ['Jet', 'Are You Gonna Be My Girl', 'tuK6n2Lkza0'],
  ['Joan Osbourne', 'One Of Us', 'aDdOnl0bHO4'],
  ['Journey', 'Don\'t Stop Believin\'', '1k8craCGpgs'],
  ['Joy Division', 'Love Will Tear Us Apart', '674KGKRQBPE'],
  ['Judas Priest', 'Breaking The Law', 'L397TWLwrUU'],
  ['Kansas', 'Dust In The Wind', 'tH2w6Oxx0kQ'],
  ['Kiss', 'I Was Made For Lovin\' You', 'ZhIsAZO5gl0'],
  ['Liquido', 'Narcotic', 'PJ7E40Ec5ec'],
  ['Living Colour', 'Cult Of Personality', '7xxgRUyzgs0'],
  ['Men At Work', 'Down Under', 'XfR9iY5y94s'],
  ['MGMT', 'Kids', 'fe4EK4HSPkI'],
  ['Michael Sembello', 'Maniac', '6GCNUeTFSbA'],
  ['Midnight Oil', 'Beds Are Burning', 'ejorQVy3m8E'],
  ['Mötley Crüe', 'Kickstart My Heart', 'CmXWkMlKFkI'],
  ['New Order', 'Blue Monday', 'c1GxjzHm5us'],
  ['Orchestral Manoeuvres In The Dark', 'Enola Gay', 'd5XJ2GiR6Bo'],
  ['Ozzy Osbourne', 'Crazy Train', 'tMDFv5m18Pw'],
  ['Pearl Jam', 'Alive', 'qM0zINtulhM'],
  ['Pet Shop Boys', 'It\'s A Sin', 'dRHetRTOD1Q'],
  ['Pixies', 'Where Is My Mind', 'OJ62RzJkYUo'],
  ['Placebo', 'Every You Every Me', 'OMaycNcPsHI'],
  ['Radiohead', 'Creep', 'XFkzRNyygfk'],
  ['Rage Against The Machine', 'Killing In The Name', 'bWXazVhlyxQ'],
  ['Rick Astley', 'Never Gonna Give You Up', 'dQw4w9WgXcQ'],
  ['Run DMC', 'Walk This Way', '4B_UYYPb-Gk'],
  ['Sade', 'Smooth Operator', '4TYv2PhG89A'],
  ['Salt-N-Pepa', 'Push It', 'vCadcBR95oU'],
  ['Simple Minds', 'Don\'t You(Forget About Me)', 'CdqoNKCCt7A'],
  ['Snow Patrol', 'Chasing Cars', 'GemKqzILV4w'],
  ['Soft Cell', 'Tainted Love', 'XZVpR3Pk-r8'],
  ['Soundgarden', 'Black Hole Sun', '3mbBbFH9fAg'],
  ['Spice Girls', 'Wannabe', 'gJLIiF15wjQ'],
  ['Survivor', 'Eye Of The Tiger', 'btPJPFnesV4'],
  ['Suzanne Vega', 'Luka', 'VZt7J0iaUD0'],
  ['Talk Talk', 'It\'s My Life', 'cFH5JgyZK1I'],
  ['Talking Heads', 'Psycho Killer', 'CKti7QixnJI'],
  ['Tears For Fears', 'Mad World', 'u1ZvPSpLxCg'],
  ['The Animals', 'House of the Rising Sun', 'N4bFqW_eu2I'],
  ['The Buggles', 'Video Killed The Radio Star', 'W8r-tXRLazs'],
  ['The Cult', 'She Sells Sanctuary', 'ZCOSPtyZAPA'],
  ['The Doors', 'Riders on the Storm', '7G2-FPlvY58'],
  ['The Human League', 'Don\'t You Want Me', 'uPudE8nDog0'],
  ['The Mamas & The Papas', 'California Dreamin\'', 'oU6uUEwZ8FM'],
  ['The Ramones', 'Blitzkrieg Bop', 'skdE0KAFCEA'],
  ['The Rolling Stones', 'Paint It Black', 'O4irXQhgMqg'],
  ['The Smashing Pumpkins', '1979', '4aeETEoNfOg'],
  ['The White Stripes', 'Seven Nation Army', '0J2QdDbelmY'],
  ['The Who', 'Behind Blue Eyes', 'KmbCOMM8peo'],
  ['Tokio Hotel', 'Monsoon', 'Le_IyYLrUtQ'],
  ['Ugly Kid Joe', 'Cats In The Cradle', 'B32yjbCSVpU'],
  ['Van Halen', 'Jump', 'SwYN7mTi6HM'],
  ['Vanilla Ice', 'Ice Ice Baby', 'rog8ou-ZepE'],
  ['Village People', 'YMCA', 'CS9OO0S5w2k'],
  ['Visage', 'Fade To Grey', 'UMPC8QJF6sI']
];
