const songs = [ // eslint-disable-line no-unused-vars
  ['Queen', 'Bohemian Rhapsody', 'fJ9rUzIMcZQ', '1975', ['Rock']],
  ['Queen', 'Don\'t Stop Me Now', 'HgzGwKwLmgM', '1978', ['Rock']],
  ['Queen', 'Another One Bites The Dust', 'rY0WxgSXdEE', '1980', ['Rock']],
  ['Queen', 'We Will Rock You', '-tJYN-eG1zk', '1977', ['Rock']],
  ['Queen', 'We Are The Champions', '04854XqcfCY', '1977', ['Rock']],
  ['Queen', 'Radio Ga Ga', 'azdwsXLmrHE', '1984', ['Rock']],
  ['Queen', 'The Show Must Go On', 't99KH0TR-J4', '1991', ['Rock']],
  ['Queen', 'Under Pressure', 'a01QQZyl-_I', '1981', ['Rock']],
  ['Coldplay', 'The Scientist', 'RB-RcX5DS5A', '2002', ['Pop Rock']],
  ['Coldplay', 'Yellow', 'yKNxeF4KMsY', '2000', ['Pop Rock']],
  ['Coldplay', 'Viva La Vida', 'dvgZkm1xWPE', '2008', ['Pop Rock']],
  ['Coldplay', 'Fix You', 'k4V3Mo61fJM', '2005', ['Pop Rock']],
  ['Coldplay', 'Paradise', '1G4isv_Fylg', '2011', ['Pop Rock']],
  ['Coldplay', 'Clocks', 'd020hcWA_Wg', '2002', ['Pop Rock']],
  ['The Offspring', 'The Kids Aren\'t Alright', '7iNbnineUCI', '1998', ['Punk Rock']],
  ['The Offspring', 'Self Esteem', 'Abrn8aVQ76Q', '1994', ['Punk Rock']],
  ['The Offspring', 'Pretty Fly (For A White Guy)', 'QtTR-_Klcq8', '1998', ['Punk Rock']],
  ['The Offspring', 'Why Don\'t You Get A Job', 'LH-i8IvYIcg', '1998', ['Punk Rock']],
  ['The Offspring', 'Want You Bad', '_g19fCJotPc', '2000', ['Punk Rock']],
  ['The Offspring', 'Gone Away', '40V9_1PMUGM', '1997', ['Punk Rock']],
  ['Red Hot Chili Peppers', 'Californication', 'YlUKcNNmywk', '1999', ['Rock']],
  ['Red Hot Chili Peppers', 'Otherside', 'rn_YodiJO6k', '1999', ['Rock']],
  ['Red Hot Chili Peppers', 'Can\'t Stop', '8DyziWtkfBw', '2002', ['Rock']],
  ['Red Hot Chili Peppers', 'By The Way', 'JnfyjwChuNU', '2002', ['Rock']],
  ['Red Hot Chili Peppers', 'Under The Bridge', 'GLvohMXgcBo', '1991', ['Rock']],
  ['Guns N\' Roses', 'Sweet Child O\' Mine', '1w7OgIMMRc4', '1987', ['Rock']],
  ['Guns N\' Roses', 'Paradise City', 'Rbm6GXllBiw', '1987', ['Rock']],
  ['Guns N\' Roses', 'November Rain', '8SbUC-UaAxE', '1991', ['Rock']],
  ['Guns N\' Roses', 'Knockin\' On Heaven\'s Door', 'k04tX2fvh0o', '1991', ['Rock']],
  ['Guns N\' Roses', 'Don\'t Cry', 'zRIbf6JqkNc', '1991', ['Rock']],
  ['Blondie', 'Heart Of Glass', 'WGU_4-5RaxU', '1978', ['New Wave']],
  ['Blondie', 'One Way Or Another', 'valVixMpzQY', '1978', ['New Wave']],
  ['Blondie', 'Call Me', 'StKVS0eI85I', '1980', ['New Wave']],
  ['Blondie', 'Atomic', 'O_WLw_0DFQQ', '1979', ['New Wave']],
  ['Blondie', 'Maria', 'abw49k3rIN0', '1999', ['New Wave']],
  ['David Bowie', 'Starman', 'aBKEt3MhNMM', '1969', ['Pop', 'Rock']],
  ['David Bowie', 'Let\'s Dance', 'VbD_kBJc_gI', '1983', ['Pop', 'Rock']],
  ['David Bowie', 'Modern Love', 'HivQqTtiHVw', '1983', ['Pop', 'Rock']],
  ['David Bowie', 'Space Oddity', 'iYYRH4apXDo', '1969', ['Pop', 'Rock']],
  ['Metallica', 'Nothing Else Matters', 'tAGnKpE4NCI', '1991', ['Metal']],
  ['Metallica', 'The Unforgiven', 'DDGhKS6bSAE', '1991', ['Metal']],
  ['Metallica', 'Fade To Black', '9HZ_tx8aWuA', '1984', ['Metal']],
  ['Metallica', 'The Day That Never Comes', 'RD83oy7ksUE', '2008', ['Metal']],
  ['The Cranberries', 'Zombie', '6Ejga4kJUts', '1994', ['Rock']],
  ['The Cranberries', 'Ode To My Family', 'Zz-DJr1Qs54', '1994', ['Rock']],
  ['The Cranberries', 'Dreams', 'Yam5uK6e-bQ', '1993', ['Rock']],
  ['The Cranberries', 'Linger', 'G6Kspj3OO0s', '1993', ['Rock']],
  ['Sum 41', 'Fat Lip', 'CMX2lPum_pg', '2001', ['Punk Rock']],
  ['Sum 41', 'Still Waiting', 'qO-mSLxih-c', '2002', ['Punk Rock']],
  ['Sum 41', 'The Hell Song', '7pE8ReA5cn4', '2002', ['Punk Rock']],
  ['Sum 41', 'Pieces', 'By7ctqcWxyM', '2004', ['Punk Rock']],
  ['blink-182', 'All The Small Things', '9Ht5RZpzPqw', '1999', ['Rock']],
  ['blink-182', 'I Miss You', 's1tAYmMjLdY', '2003', ['Rock']],
  ['blink-182', 'First Date', 'vVy9Lgpg1m8', '2001', ['Rock']],
  ['blink-182', 'Adam\'s Song', '2MRdtXWcgIw', '1999', ['Rock']],
  ['The Rasmus', 'In The Shadows', '7gwO8-oqwFw', '2003', ['Rock']],
  ['The Rasmus', 'Guilty', 'eOdr_FlBPBk', '2003', ['Rock']],
  ['The Rasmus', 'Sail Away', 'pL-i4Lcgk2w', '2005', ['Rock']],
  ['The Rasmus', 'First Day Of My Life', 'oBvbX571P3s', '2003', ['Rock']],
  ['Rise Against', 'Savior', 'e8X3ACToii0', '2008', ['Rock']],
  ['Rise Against', 'Prayer Of The Refugee', '9-SQGOYOjxs', '2006', ['Rock']],
  ['Rise Against', 'Hero Of War', '_DboMAghWcA', '2008', ['Rock']],
  ['Rise Against', 'Give It All', 'dhldbymXK-8', '2004', ['Rock']],
  ['ABBA', 'Gimme! Gimme! Gimme! (A Man After Midnight)', 'XEjLoHdbVeE', '1979', ['Pop']],
  ['ABBA', 'Dancing Queen', 'xFrGuyw1V8s', '1976', ['Pop']],
  ['ABBA', 'Lay All Your Love On Me', 'ulZQTrV8QlQ', '1980', ['Pop']],
  ['ABBA', 'Mamma Mia', 'unfzfe8f9NI', '1975', ['Pop']],
  ['Linkin Park', 'In The End', 'eVTXPUF4Oz4', '2000', ['Nu Metal']],
  ['Linkin Park', 'Numb', 'kXYiU_JCYtU', '2003', ['Nu Metal']],
  ['Linkin Park', 'What I\'ve Done', '8sgycukafqQ', '2007', ['Nu Metal']],
  ['Green Day', 'Wake Me Up When September Ends', 'NU9JoFKlaZ0', '2005', ['Rock']],
  ['Green Day', 'Boulevard Or Broken Dreams', 'Soa3gO7tL-c', '2004', ['Rock']],
  ['Green Day', 'Holiday', 'A1OqtIqzScI', '2004', ['Rock']],
  ['System Of A Down', 'Chop Suey!', 'CSvFpBOe8eY', '2001', ['Nu Metal']],
  ['System Of A Down', 'Aerials', 'L-iepu3EtyE', '2001', ['Nu Metal']],
  ['System Of A Down', 'Lonely Day', 'DnGdoEa1tPg', '2005', ['Nu Metal']],
  ['Nirvana', 'Smells Like Teen Spirit', 'hTWKbfoikeg', '1991', ['Rock']],
  ['Nirvana', 'Come As You Are', 'ZEMBDKMtHqM', '1991', ['Rock']],
  ['Nirvana', 'Lithium', 'pkcJEvMcnEg', '1991', ['Rock']],
  ['Oasis', 'Wonderwall', 'bx1Bh8ZvH84', '1995', ['Rock']],
  ['Oasis', 'Don\'t Look Back In Anger', 'r8OipmKFDeM', '1995', ['Rock']],
  ['Oasis', 'Stop Crying Your Heart Out', '6QyVil0dwhk', '2002', ['Rock']],
  ['Scorpions', 'Wind Of Change', 'n4RjJKxsamQ', '1990', ['Hard Rock']],
  ['Scorpions', 'Rock You Like A Hurricane', 'UCxgbOBVSfM', '1984', ['Hard Rock']],
  ['Scorpions', 'Send Me An Angel', '1UUYjd2rjsE', '1983', ['Hard Rock']],
  ['AC/DC', 'Highway To Hell', 'l482T0yNkeo', '1979', ['Rock']],
  ['AC/DC', 'Thunderstruck', 'v2AC41dglnM', '1990', ['Rock']],
  ['AC/DC', 'You Shook Me All Night Long', 'Lo2qQmj0_h4', '1980', ['Rock']],
  ['Aerosmith', 'I Don\'t Want To Miss A Thing', 'JkK8g6FMEXE', '1998', ['Rock']],
  ['Aerosmith', 'Crazy', 'NMNgbISmF4I', '1993', ['Rock']],
  ['Aerosmith', 'Cryin\'', 'qfNmyxV2Ncw', '1993', ['Rock']],
  ['R.E.M.', 'Losing My Religion', 'xwtdhWltSIg', '1991', ['Rock']],
  ['R.E.M.', 'Everybody Hurts', '5rOiW_xY-kc', '1992', ['Rock']],
  ['R.E.M.', 'Shiny Happy People', 'YYOKMUTTDdA', '1991', ['Rock']],
  ['The Beatles', 'Come Together', '45cYwDMibGo', '1969', ['Rock']],
  ['The Beatles', 'Let It Be', 'QDYfEBY9NM4', '1970', ['Rock']],
  ['The Beatles', 'Hey Jude', 'A_MjCqQoLLA', '1968', ['Rock']],
  ['The Clash', 'Should I Stay or Should I Go', 'BN1WwnEDWAM', '1981', ['Rock']],
  ['The Clash', 'London Calling', 'a3XqMtam1I0', '1979', ['Rock']],
  ['The Clash', 'Rock the Casbah', 'LJTk64tzduQ', '1982', ['Rock']],
  ['The Cure', 'Lovesong', 'ks_qOI0lzho', '1989', ['Pop', 'Rock']],
  ['The Cure', 'Lullaby', 'ijxk-fgcg7c', '1989', ['Pop', 'Rock']],
  ['The Cure', 'Just Like Heaven', 'n3nPiBai66M', '1989', ['Pop', 'Rock']],
  ['The Police', 'Every Breath You Take', 'OMOGaugKpzs', '1983', ['New Wave']],
  ['The Police', 'Roxanne', '3T1c7GkzRQQ', '1978', ['New Wave']],
  ['The Police', 'Message In A Bottle', 'MbXWrmQW-OE', '1979', ['New Wave']],
  ['Papa Roach', 'Last Resort', 'j0lSpNtjPM8', '2000', ['Rock']],
  ['Papa Roach', 'Scars', 'eHbNU9WuVgw', '2004', ['Rock']],
  ['Papa Roach', 'Between Angels And Insects', 'H2jCbXiEQI4', '2000', ['Rock']],
  ['Limp Bizkit', 'Rollin\'', 'RYnFIRc0k6E', '2000', ['Nu Metal']],
  ['Limp Bizkit', 'Behind Blue Eyes', 'Tr8uesBowS4', '2003', ['Nu Metal']],
  ['Limp Bizkit', 'My Way', 'Dn8vzTsnPps', '2000', ['Nu Metal']],
  ['Rammstein', 'Du Hast', 'W3q8Od5qJio', '1997', ['Rock']],
  ['Rammstein', 'Amerika', 'Rr8ljRgcJNM', '2004', ['Rock']],
  ['Rammstein', 'Ohne Dich', 'LIPc1cfS-oQ', '2004', ['Rock']],
  ['3 Doors Down', 'Kryptonite', 'xPU8OAjjS4k', '2000', ['Rock']],
  ['3 Doors Down', 'Here Without You', 'kPBzTxZQG5Q', '2003', ['Rock']],
  ['3 Doors Down', 'When I\'m Gone', 'pFq1eT9tMJ4', '2002', ['Rock']],
  ['Bon Jovi', 'Livin\' On A Prayer', 'lDK9QqIzhwk', '1986', ['Rock']],
  ['Bon Jovi', 'You Give Love A Bad Name', 'KrZHPOeOxQQ', '1986', ['Rock']],
  ['Bon Jovi', 'It\'s My Life', 'vx2u5uUu3DE', '2000', ['Rock']],
  ['Duran Duran', 'Hungry Like The Wolf', 'oJL-lCzEXgI', '1982', ['New Wave']],
  ['Duran Duran', 'Come Undone', 'Epj84QVw2rc', '1993', ['New Wave']],
  ['Duran Duran', 'Ordinary World', 'FqIACCH20JU', '1993', ['New Wave']],
  ['Sting', 'Englishman In New York', 'd27gTrPPAyk', '1987', ['Pop']],
  ['Sting', 'Shape Of My Heart', 'NlwIDxCjL-8', '1993', ['Pop']],
  ['Sting', 'Desert Rose', 'C3lWwBslWqg', '1999', ['Pop']],
  ['Savage Garden', 'Truly Madly Deeply', 'WQnAxOQxQIU', '1997', ['Pop']],
  ['Savage Garden', 'I Knew I Loved You', 'jjnmICxvoVY', '1999', ['Pop']],
  ['Savage Garden', 'To The Moon & Back', 'HCm6gRHINqA', '1997', ['Pop']],
  ['Toto', 'Africa', 'FTQbiNvZqaY', '1982', ['Rock']],
  ['Toto', 'Hold the Line', 'htgr3pvBr-I', '1978', ['Rock']],
  ['Toto', 'Rosanna', 'qmOLtTGvsbM', '1982', ['Rock']],
  ['t.A.T.u.', 'All The Things You Said', '8mGBaXPlri8', '2002', ['Pop']],
  ['t.A.T.u.', 'All About Us', '6yP4Nm86yk0', '2005', ['Pop']],
  ['t.A.T.u.', 'Not Gonna Get Us', '0HL-N9oOjcs', '2002', ['Pop']],
  ['Roxette', 'It Must Have Been Love', 'k2C5TjS2sh4', '1987', ['Pop']],
  ['Roxette', 'Listen To Your Heart', 'yCC_b5WHLX0', '1988', ['Pop']],
  ['Roxette', 'The Look', 'LlVI7ZNiFlI', '1988', ['Pop']],
  ['Iron Maiden', 'Run To The Hills', '86URGgqONvA', '1982', ['Heavy Metal']],
  ['Iron Maiden', 'Fear Of The Dark', 'bePCRKGUwAY', '1992', ['Heavy Metal']],
  ['Led Zeppelin', 'Immigrant Song', 'RlNhD0oS5pk', '1970', ['Rock']],
  ['Led Zeppelin', 'Stairway to Heaven', 'QkF3oxziUI4', '1971', ['Rock']],
  ['Pink Floyd', 'Another Brick In The Wall Part 2', 'HrxX9TBj2zY', '1979', ['Rock']],
  ['Pink Floyd', 'Wish You Were Here', '84Tq-eAJIk4', '1975', ['Rock']],
  ['Joan Jett & The Blackhearts', 'I Love Rock \'N Roll', 'wMsazR6Tnf8', '1981', ['Rock']],
  ['Joan Jett & The Blackhearts', 'I Hate Myself For Loving You', 'bpNw7jYkbVc', '1988', ['Rock']],
  ['Creedence Clearwater Revival', 'Have You Ever Seen The Rain', 'u1V8YRJnr4Q', '1971', ['Rock']],
  ['Creedence Clearwater Revival', 'Fortunate Son', 'ZWijx_AgPiA', '1969', ['Rock']],
  ['Elton John', 'Rocket Man', 'DtVBCG6ThDk', '1972', ['Rock']],
  ['Elton John', 'Saturday Night\'s Alright (For Fighting)', 'AhnZEmnuzgM', '1973', ['Rock']],
  ['Frank Sinatra', 'My Way', 'qQzdAsjWGPg', '1969', ['Pop']],
  ['Frank Sinatra', 'Fly Me To The Moon', 'ZEcqHA7dbwM', '1954', ['Pop']],
  ['The Verve', 'Bitter Sweet Symphony', '1lyu1KKwC74', '1997', ['Rock']],
  ['The Verve', 'The Drugs Don\'t Work', 'ToQ0n3itoII', '1997', ['Rock']],
  ['Simple Plan', 'Welcome To My Life', 'r0U0AlLVqpk', '2004', ['Rock']],
  ['Simple Plan', 'Perfect', 'RUi54JTgL5s', '2002', ['Rock']],
  ['Three Days Grace', 'I Hate Everything About You', 'ph9KP2_lT5Q', '2003', ['Rock']],
  ['Three Days Grace', 'Never Too Late', 'lL2ZwXj1tXM', '2006', ['Rock']],
  ['Thirty Seconds To Mars', 'The Kill', '8yvGCAvOAfM', '2005', ['Alternative Rock']],
  ['Thirty Seconds To Mars', 'This Is War', 'Zcps2fJKuAI', '2009', ['Alternative Rock']],
  ['Alice Cooper', 'Poison', 'Qq4j1LtCdww', '1989', ['Rock']],
  ['Alice Cooper', 'School\'s Out', '2Oo8QzDHimQ', '1972', ['Rock']],
  ['Alphaville', 'Big In Japan', 'tl6u2NASUzU', '1984', ['Pop']],
  ['Alphaville', 'Forever Young', 'oNjQXmoxiQ8', '1984', ['Pop']],
  ['Backstreet Boys', 'Everybody (Backstreet\'s Back', '6M6samPEMpM', '1997', ['Pop']],
  ['Backstreet Boys', 'I Want It That Way', '4fndeDfaWCg', '1999', ['Pop']],
  ['Boney M.', 'Rasputin', '16y1AkoZkmQ', '1978', ['Pop']],
  ['Boney M.', 'Daddy Cool', 'FYGTT7YhywA', '1976', ['Pop']],
  ['Bonnie Tyler', 'Total Eclipse of the Heart', 'lcOxhH8N3Bo', '1983', ['Pop', 'Rock']],
  ['Bonnie Tyler', 'Holding Out For A Hero', 'bWcASV2sey0', '1984', ['Pop', 'Rock']],
  ['Cyndi Lauper', 'Girls Just Want To Have Fun', 'PIb6AZdTr-A', '1983', ['Pop']],
  ['Cyndi Lauper', 'Time After Time', 'VdQY7BusJNU', '1983', ['Pop']],
  ['Suzanne Vega', 'Luka', 'VZt7J0iaUD0', '1987', ['Pop']],
  ['Suzanne Vega', 'Tom\'s Diner', 'j4jtIDaeaWI', '1987', ['Pop']],
  ['Whitney Houston', 'I Will Always Love You', '3JWTaaS7LdU', '1974', ['Pop']],
  ['Whitney Houston', 'I Wann Dance With Somebody', 'eH3giaIzONA', '1987', ['Pop']],
  ['Depeche Mode', 'Personal Jesus', 'u1xrNaTO1bI', '1990', ['Pop', 'Synth-Pop']],
  ['Depeche Mode', 'Enjoy The Silence', 'aGSKrC7dGcY', '1990', ['Pop', 'Synth-Pop']],
  ['Eurythmics, Annie Lennox, Dave Stewart', 'Sweet Dreams (Are Made Of This)', 'qeMFqkcPYcg', '1983', ['Pop']],
  ['Eurythmics, Annie Lennox, Dave Stewart', 'Here Comes The Rain Again', 'TzFnYcIqj6I', '1983', ['Pop']],
  ['Beastie Boys', 'Sabotage', 'z5rRZdiu1UE', '1994', ['Pop', 'Alternative-Hip-Hop']],
  ['Beastie Boys', 'Intergalactic', 'qORYO0atB6g', '1998', ['Pop', 'Alternative-Hip-Hop']],
  ['Billy Idol', 'Rebel Yell', 'VdphvuyaV_I', '1983', ['Rock']],
  ['Billy Idol', 'White Wedding', 'AAZQaYKZMTI', '1982', ['Rock']],
  ['Evanescence', 'Bring Me To Life', '3YxaaGgTQYM', '2003', ['Alternative Rock']],
  ['Evanescence', 'My Immortal', '5anLPw0Efmo', '2003', ['Alternative Rock']],
  ['No Doubt', 'Don\'t Speak', 'TR3Vdo5etCQ', '1996', ['Rock']],
  ['No Doubt', 'Just A Girl', 'PHzOOQfhPFg', '1995', ['Rock']],
  ['Spice Girls', 'Wannabe', 'gJLIiF15wjQ', '1996', ['Pop']],
  ['Spice Girls', 'Viva Forever', '3wkuqRFXNvI', '1997', ['Pop']],
  ['The Cardigans', 'Lovefool', 'NI6aOFI7hms', '1996', ['Rock']],
  ['The Cardigans', 'My Favourite Game', 'u9WgtlgGAgs', '1998', ['Rock']],
  ['The Killers', 'Mr. Brightside', 'gGdGFtwCNBE', '2004', ['Rock']],
  ['The Killers', 'Somebody Told Me', 'Y5fBdpreJiU', '2004', ['Rock']],
  ['4 Non Blondes', 'What\'s Up', '6NXnxTNIWkc', '1992', ['Alternative Rock']],
  ['a-ha', 'Take On Me', 'djV11Xbc914', '1985', ['Pop']],
  ['Ace of Base', 'All That She Wants', 'd73tiBBzvFM', '1992', ['Pop']],
  ['Alanis Morissette', 'Ironic', 'Jne9t8sHpUc', '1996', ['Alternative Rock']],
  ['Alien Ant Farm', 'Smooth Criminal', 'CDl9ZMfj6aE', '2001', ['Rock']],
  ['Bee Gees', 'Stayin\' Alive', 'I_izvAbhExY', '1977', ['Pop']],
  ['Berlin', 'Take My Breath Away', 'Bx51eegLTY8', '1986', ['Pop']],
  ['Black Sabbath', 'Paranoid', '0qanF-91aJo', '1970', ['Hard Rock']],
  ['Blind Melon', 'No Rain', '3qVPNONdF58', '1992', ['Rock']],
  ['Blur', 'Song 2', 'SSbBvKaM6sk', '1997', ['Rock']],
  ['Bomfunk MC\'s', 'Freestyler', 'ymNFyxvIdaM', '1999', ['Pop', 'Electro-Hip-Hop']],
  ['Bronski Beat', 'Smalltown Boy', '88sARuFu-tc', '1984', ['Pop', 'Synth-Pop']],
  ['Chumbawamba', 'Tubthumping', '2H5uWRjFsGc', '1997', ['Rock']],
  ['Coolio', 'Gangsta\'s Paradise', 'fPO76Jlnz6c', '1995', ['Pop', 'Hip Hop']],
  ['Cutting Crew', '(I Just) Died In Your Arms', '6dOwHzCHfgA', '1986', ['Pop']],
  ['Dead Or Alive', 'You Spin Me Round (Like A Record)', 'PGNiXGX2nLU', '1985', ['Pop']],
  ['Deep Purple', 'Smoke On The Water', 'eu5lv2Umn3M', '1972', ['Rock']],
  ['Dire Straits', 'Sultans of Swing', 'h0ffIJ7ZO4U', '1978', ['Rock']],
  ['Don Henley', 'The Boys Of Summer', '6RUIeX6UCT8', '1984', ['Rock']],
  ['Eagles', 'Hotel California', 'BciS5krYL80', '1976', ['Rock']],
  ['Empire Of The Sun', 'We Are The People', 'hN5X4kGhAtU', '2008', ['Pop', 'Synth-Pop']],
  ['Earth, Wind & Fire', 'September', 'Gs069dndIYk', '1978', ['Pop']],
  ['Europe', 'The Final Countdown', '9jK-NcRmVcw', '1986', ['Rock']],
  ['Falco', 'Rock Me Amadeus', 'cVikZ8Oe_XA', '1985', ['New Wave']],
  ['Fleetwood Mac', 'Go Your Own Way', 'ozl3L9fhKtE', '1976', ['Rock']],
  ['Foster The People', 'Pumped Up Kicks', 'SDTZ7iX4vTQ', '2011', ['Pop', 'Indie Pop']],
  ['Frankie Goes To Hollywood', 'Relax', 'Yem_iEHiyJ0', '1984', ['Pop']],
  ['Frankie Valli and the Four Seasons', 'Can\' Take My Eyes Off You', 'DYwQy_9JPtQ', '1967', ['Pop']],
  ['Gorillaz', 'Feel Good Inc.', 'HyHNuVaZJ-k', '2005', ['Rock']],
  ['Heart', 'Alone', '1Cw1ng75KP0', '1987', ['Hard Rock']],
  ['Hoobastank', 'The Reason', 'fV4DiAyExN0', '2003', ['Rock']],
  ['Iggy Pop', 'The Passenger', '-fWw7FE9tTo', '1977', ['Rock']],
  ['INXS', 'Need You Tonight', 'F93ywiGMDnQ', '1987', ['Rock']],
  ['Jet', 'Are You Gonna Be My Girl', 'tuK6n2Lkza0', '2003', ['Rock']],
  ['Joan Osbourne', 'One Of Us', 'aDdOnl0bHO4', '1995', ['Pop Rock']],
  ['Journey', 'Don\'t Stop Believin\'', '1k8craCGpgs', '1981', ['Rock']],
  ['Joy Division', 'Love Will Tear Us Apart', '674KGKRQBPE', '1980', ['Rock']],
  ['Judas Priest', 'Breaking The Law', 'L397TWLwrUU', '1980', ['Heavy Metal']],
  ['Kansas', 'Dust In The Wind', 'tH2w6Oxx0kQ', '1977', ['Rock']],
  ['Kiss', 'I Was Made For Lovin\' You', 'ZhIsAZO5gl0', '1979', ['Rock']],
  ['Liquido', 'Narcotic', 'PJ7E40Ec5ec', '1999', ['Rock']],
  ['Living Colour', 'Cult Of Personality', '7xxgRUyzgs0', '1988', ['Rock']],
  ['Men At Work', 'Down Under', 'XfR9iY5y94s', '1981', ['Rock']],
  ['MGMT', 'Kids', 'fe4EK4HSPkI', '2007', ['Pop', 'Synth-Pop']],
  ['Michael Sembello', 'Maniac', '6GCNUeTFSbA', '1983', ['Rock']],
  ['Midnight Oil', 'Beds Are Burning', 'ejorQVy3m8E', '1987', ['Rock']],
  ['Mötley Crüe', 'Kickstart My Heart', 'CmXWkMlKFkI', '1989', ['Glam Metal']],
  ['Neil Young', 'Rockin\' In The Free World', 'TnAgc1kgvLc', '1991', ['Rock']],
  ['New Order', 'Blue Monday', 'c1GxjzHm5us', '1983', ['New Wave', 'Post Punk']],
  ['Orchestral Manoeuvres In The Dark', 'Enola Gay', 'd5XJ2GiR6Bo', '1980', ['Pop', 'Synth-Pop']],
  ['Ozzy Osbourne', 'Crazy Train', 'tMDFv5m18Pw', '1980', ['Heavy Metal']],
  ['Pearl Jam', 'Alive', 'qM0zINtulhM', '1991', ['Rock']],
  ['Pet Shop Boys', 'It\'s A Sin', 'dRHetRTOD1Q', '1987', ['Pop', 'Synth-Pop']],
  ['Pixies', 'Where Is My Mind', 'OJ62RzJkYUo', '1988', ['Rock']],
  ['Placebo', 'Every You Every Me', 'OMaycNcPsHI', '1998', ['Rock']],
  ['Radiohead', 'Creep', 'XFkzRNyygfk', '1993', ['Rock']],
  ['Rage Against The Machine', 'Killing In The Name', 'bWXazVhlyxQ', '1992', ['Rock']],
  ['Rick Astley', 'Never Gonna Give You Up', 'dQw4w9WgXcQ', '1987', ['Pop']],
  ['Run DMC', 'Walk This Way', '4B_UYYPb-Gk', '1987', ['Hip Hop']],
  ['Sade', 'Smooth Operator', '4TYv2PhG89A', '1984', ['Pop']],
  ['Salt-N-Pepa', 'Push It', 'vCadcBR95oU', '1986', ['Pop', 'Hip Hop']],
  ['Simple Minds', 'Don\'t You(Forget About Me)', 'CdqoNKCCt7A', '1985', ['Rock']],
  ['Snow Patrol', 'Chasing Cars', 'GemKqzILV4w', '2006', ['Rock']],
  ['Soft Cell', 'Tainted Love', 'XZVpR3Pk-r8', '1981', ['Pop', 'Synth-Pop']],
  ['Soundgarden', 'Black Hole Sun', '3mbBbFH9fAg', '1994', ['Rock']],
  ['Survivor', 'Eye Of The Tiger', 'btPJPFnesV4', '1982', ['Rock']],
  ['Talk Talk', 'It\'s My Life', 'cFH5JgyZK1I', '1984', ['Pop', 'Synth-Pop']],
  ['Talking Heads', 'Psycho Killer', 'CKti7QixnJI', '1977', ['Rock']],
  ['Tears For Fears', 'Mad World', 'u1ZvPSpLxCg', '1983', ['Pop', 'Synth-Pop']],
  ['The Animals', 'House of the Rising Sun', 'N4bFqW_eu2I', '1964', ['Rock']],
  ['The Buggles', 'Video Killed The Radio Star', 'W8r-tXRLazs', '1979', ['Pop']],
  ['The Cult', 'She Sells Sanctuary', 'ZCOSPtyZAPA', '1985', ['Rock']],
  ['The Doors', 'Riders on the Storm', '7G2-FPlvY58', '1971', ['Rock']],
  ['The Human League', 'Don\'t You Want Me', 'uPudE8nDog0', '1981', ['New Wave']],
  ['The Mamas & The Papas', 'California Dreamin\'', 'oU6uUEwZ8FM', '1965', ['Rock']],
  ['The Ramones', 'Blitzkrieg Bop', 'skdE0KAFCEA', '1976', ['Rock']],
  ['The Rolling Stones', 'Paint It Black', 'O4irXQhgMqg', '1966', ['Rock']],
  ['The Smashing Pumpkins', '1979', '4aeETEoNfOg', '1995', ['Rock']],
  ['The White Stripes', 'Seven Nation Army', '0J2QdDbelmY', '2003', ['Rock']],
  ['The Who', 'Behind Blue Eyes', 'KmbCOMM8peo', '1971', ['Rock']],
  ['Tokio Hotel', 'Monsoon', 'Le_IyYLrUtQ', '2007', ['Pop', 'Rock']],
  ['UFO', 'Doctor Doctor', 'J-U5H6hmw6E', '1974', ['Rock']],
  ['Ugly Kid Joe', 'Cats In The Cradle', 'B32yjbCSVpU', '1992', ['Rock']],
  ['Van Halen', 'Jump', 'SwYN7mTi6HM', '1984', ['Rock']],
  ['Vanilla Ice', 'Ice Ice Baby', 'rog8ou-ZepE', '1990', ['Pop', 'Hip Hop']],
  ['Village People', 'YMCA', 'CS9OO0S5w2k', '1978', ['Pop']],
  ['Laura Branigan', 'Self Control', 'RP0_8J7uxhs', '1984', ['Pop']],
  ['Paula Abdul', 'Straight Up', 'El1kgCqD7Xk', '1988', ['Pop']],
  ['Taylor Dayne', 'Tell It To My Heart', 'Ud6sU3AclT4', '1988', ['Pop']],
  ['Kim Wilde', 'You Keep Me Hangin On', 'xJZF-skCY-M', '1986', ['Pop']],
  ['The Bangles', 'Eternal Flame', 'PSoOFn3wQV4', '1988', ['Soft Rock']],
  ['Mike Oldfield', 'Moonlight Shadow', 'e80qhyovOnA', '1983', ['Pop']],
  ['Celine Dion', 'It\'s All Coming Back to Me Now', 'j8fHNdrZTSI', '1996', ['Pop']],
  ['Shania Twain', 'You\'re Still the One', 'KNZH-emehxA', '1997', ['Pop']],
  ['LeAnn Rimes', 'Can\'t Fight The Moonlight', 'bx3s99FNXzI', '2001', ['Pop']],
  ['Crowded House', 'Don\'t Dream It\'s Over', 'J9gKyRmic20', '1986', ['Rock', 'New Wave]],
  ['Fugees', 'Killing Me Softly With His Song', 'oKOtzIo-uYw', '1996', ['R&B', 'Hip-Hop Soul']],
  ['Roberta Flack', 'Killing Me Softly With His Song', 'mrudT410TAI', '1973', ['Soul', 'Blues', 'Pop']],
  ['King Harvest', 'Dancing in the Moonlight', 'g5JqPxmYhlo', '1973', ['Pop']],
  ['Toploader', 'Dancing in the Moonlight', 'GSWcy-bx_lg', '2000', ['Pop']],
  ['The Ronettes', 'Be My Baby', 'jSPpbOGnFgk', '1964', ['Pop']],
  ['The Righteous Brothers', 'Unchained Melody', 'IYj2hex99gY', '1965', ['Pop']],
  ['Foreigner', 'I Want to Know What Love Is', 'r3Pr1_v7hsw', '1984', ['Rock', 'Soft Rock']],
  ['Visage', 'Fade To Grey', 'UMPC8QJF6sI', '1980', ['New Wave']]
];
